apiVersion: v1 
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
data:
  RABBITMQ_HOST: "rabbitmq-cluster-ip-service"
  RABBITMQ_PORT: "5672"
# Note: changing anything here will kill the pods associated with this configmap file, 
# We don't need to change from different locatons. (Avoid redendancy)